import { REGION_CODE_BY_NAME } from "./region-catalog";

export type RegionDashboardRecord = {
  name: string;
  district: "동남구" | "서북구";
  kind: "읍" | "면" | "동";
  total: number;
  elderly: number;
  elderlyRate: number;
  ageBands: number[] | null;
  ageComposition: number[] | null;
  livingAlone: number | null;
  basicLiving: number | null;
  lowIncome: number | null;
  disabled: number | null;
  medicalInstitutions: number | null;
  publicInstitutions: number | null;
  medicalPer1000: number | null;
  areaKm2: number | null;
  stops: number | null;
  dailySupply: number | null;
  selectionReason: string;
  coreArea: string;
  policyRecommendation: string;
};

const REGION_DATA_BY_NAME: Record<string, RegionDashboardRecord> = {
  "동면": {
    "name": "동면",
    "district": "동남구",
    "kind": "면",
    "total": 1864,
    "elderly": 1020,
    "elderlyRate": 54.72,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 285,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 153,
    "medicalInstitutions": 0,
    "publicInstitutions": 2,
    "medicalPer1000": 0,
    "areaKm2": 42.9355,
    "stops": 71,
    "dailySupply": 1907,
    "selectionReason": "고령인구 비율이 높음, 심한 장애인 비율이 높음, 고령인구 대비 의료기관이 부족함",
    "coreArea": "교통",
    "policyRecommendation": "방문의료 우선 배정 / 독거노인·중증장애인 대상군 우선 확인 / 보건지소 연계 이동진료·방문진료 확대 / 예약형 셔틀·수요응답형 교통 지원"
  },
  "성남면": {
    "name": "성남면",
    "district": "동남구",
    "kind": "면",
    "total": 2734,
    "elderly": 1328,
    "elderlyRate": 48.57,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 308,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 179,
    "medicalInstitutions": 0,
    "publicInstitutions": 3,
    "medicalPer1000": 0,
    "areaKm2": 33.2031,
    "stops": 99,
    "dailySupply": 2349,
    "selectionReason": "고령인구 대비 의료기관이 부족함, 대중교통 접근성이 취약함, 고령인구 비율이 높음",
    "coreArea": "교통",
    "policyRecommendation": "방문의료 우선 배정 / 독거노인·중증장애인 대상군 우선 확인 / 보건지소 연계 이동진료·방문진료 확대 / 예약형 셔틀·수요응답형 교통 지원"
  },
  "북면": {
    "name": "북면",
    "district": "동남구",
    "kind": "면",
    "total": 3976,
    "elderly": 1726,
    "elderlyRate": 43.41,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 414,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 188,
    "medicalInstitutions": 2,
    "publicInstitutions": 2,
    "medicalPer1000": 1.16,
    "areaKm2": 58.1125,
    "stops": 97,
    "dailySupply": 4374,
    "selectionReason": "고령인구 대비 의료기관이 부족함, 대중교통 접근성이 취약함, 고령인구 비율이 높음",
    "coreArea": "교통",
    "policyRecommendation": "방문의료 우선 배정 / 보건지소 연계 이동진료·방문진료 확대 / 예약형 셔틀·수요응답형 교통 지원"
  },
  "수신면": {
    "name": "수신면",
    "district": "동남구",
    "kind": "면",
    "total": 1982,
    "elderly": 946,
    "elderlyRate": 47.73,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 221,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 60,
    "medicalInstitutions": 0,
    "publicInstitutions": 2,
    "medicalPer1000": 0,
    "areaKm2": 26.4446,
    "stops": 61,
    "dailySupply": 1775,
    "selectionReason": "고령인구 대비 의료기관이 부족함, 대중교통 접근성이 취약함, 고령인구 비율이 높음",
    "coreArea": "교통",
    "policyRecommendation": "방문의료 우선 배정 / 보건지소 연계 이동진료·방문진료 확대 / 예약형 셔틀·수요응답형 교통 지원"
  },
  "광덕면": {
    "name": "광덕면",
    "district": "동남구",
    "kind": "면",
    "total": 3950,
    "elderly": 1857,
    "elderlyRate": 47.01,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 448,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 166,
    "medicalInstitutions": 0,
    "publicInstitutions": 3,
    "medicalPer1000": 0,
    "areaKm2": 80.5878,
    "stops": 101,
    "dailySupply": 4653,
    "selectionReason": "고령인구 대비 의료기관이 부족함, 대중교통 접근성이 취약함, 고령인구 비율이 높음",
    "coreArea": "교통",
    "policyRecommendation": "방문의료 우선 배정 / 보건지소 연계 이동진료·방문진료 확대 / 예약형 셔틀·수요응답형 교통 지원"
  },
  "원성1동": {
    "name": "원성1동",
    "district": "동남구",
    "kind": "동",
    "total": 7469,
    "elderly": 2316,
    "elderlyRate": 31.01,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 492,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 215,
    "medicalInstitutions": 8,
    "publicInstitutions": 0,
    "medicalPer1000": 3.45,
    "areaKm2": 7.2769,
    "stops": 34,
    "dailySupply": 3982,
    "selectionReason": "공공 보건기관이 부족함, 고령인구 대비 의료기관이 부족함, 대중교통 접근성이 취약함",
    "coreArea": "의료",
    "policyRecommendation": "집중 모니터링 및 순회방문 / 보건지소 연계 이동진료·방문진료 확대 / 예약형 셔틀·수요응답형 교통 지원 / 인접 공공기관 또는 협력의료기관 거점 지정"
  },
  "병천면": {
    "name": "병천면",
    "district": "동남구",
    "kind": "면",
    "total": 5837,
    "elderly": 2056,
    "elderlyRate": 35.22,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 494,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 192,
    "medicalInstitutions": 11,
    "publicInstitutions": 2,
    "medicalPer1000": 5.35,
    "areaKm2": 55.1889,
    "stops": 119,
    "dailySupply": 3236,
    "selectionReason": "대중교통 접근성이 취약함, 고령인구 대비 의료기관이 부족함, 독거노인 비율이 높음",
    "coreArea": "교통",
    "policyRecommendation": "집중 모니터링 및 순회방문 / 보건지소 연계 이동진료·방문진료 확대 / 예약형 셔틀·수요응답형 교통 지원"
  },
  "입장면": {
    "name": "입장면",
    "district": "서북구",
    "kind": "면",
    "total": 7328,
    "elderly": 2750,
    "elderlyRate": 37.53,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 659,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 190,
    "medicalInstitutions": 10,
    "publicInstitutions": 3,
    "medicalPer1000": 3.64,
    "areaKm2": 42.619,
    "stops": 145,
    "dailySupply": 4735,
    "selectionReason": "고령인구 대비 의료기관이 부족함, 대중교통 접근성이 취약함, 고령인구 비율이 높음",
    "coreArea": "교통",
    "policyRecommendation": "집중 모니터링 및 순회방문 / 예약형 셔틀·수요응답형 교통 지원"
  },
  "원성2동": {
    "name": "원성2동",
    "district": "동남구",
    "kind": "동",
    "total": 8493,
    "elderly": 2856,
    "elderlyRate": 33.63,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 568,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 224,
    "medicalInstitutions": 7,
    "publicInstitutions": 0,
    "medicalPer1000": 2.45,
    "areaKm2": 0.8538,
    "stops": 13,
    "dailySupply": 5443,
    "selectionReason": "공공 보건기관이 부족함, 고령인구 대비 의료기관이 부족함, 대중교통 접근성이 취약함",
    "coreArea": "의료",
    "policyRecommendation": "집중 모니터링 및 순회방문 / 보건지소 연계 이동진료·방문진료 확대 / 인접 공공기관 또는 협력의료기관 거점 지정"
  },
  "쌍용3동": {
    "name": "쌍용3동",
    "district": "서북구",
    "kind": "동",
    "total": 16753,
    "elderly": 3286,
    "elderlyRate": 19.61,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 746,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 554,
    "medicalInstitutions": 15,
    "publicInstitutions": 0,
    "medicalPer1000": 4.56,
    "areaKm2": 1.5918,
    "stops": 19,
    "dailySupply": 2581,
    "selectionReason": "공공 보건기관이 부족함, 고령인구 대비 의료기관이 부족함, 대중교통 접근성이 취약함",
    "coreArea": "의료",
    "policyRecommendation": "집중 모니터링 및 순회방문 / 보건지소 연계 이동진료·방문진료 확대 / 인접 공공기관 또는 협력의료기관 거점 지정"
  },
  "성정1동": {
    "name": "성정1동",
    "district": "서북구",
    "kind": "동",
    "total": 16778,
    "elderly": 3727,
    "elderlyRate": 22.21,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 790,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 348,
    "medicalInstitutions": 12,
    "publicInstitutions": 0,
    "medicalPer1000": 3.22,
    "areaKm2": 1.4342,
    "stops": 17,
    "dailySupply": 4624,
    "selectionReason": "공공 보건기관이 부족함, 고령인구 대비 의료기관이 부족함, 대중교통 접근성이 취약함",
    "coreArea": "의료",
    "policyRecommendation": "집중 모니터링 및 순회방문 / 보건지소 연계 이동진료·방문진료 확대 / 인접 공공기관 또는 협력의료기관 거점 지정"
  },
  "봉명동": {
    "name": "봉명동",
    "district": "동남구",
    "kind": "동",
    "total": 17048,
    "elderly": 3498,
    "elderlyRate": 20.52,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 728,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 359,
    "medicalInstitutions": 6,
    "publicInstitutions": 0,
    "medicalPer1000": 1.72,
    "areaKm2": 1.5702,
    "stops": 23,
    "dailySupply": 3910,
    "selectionReason": "공공 보건기관이 부족함, 고령인구 대비 의료기관이 부족함, 대중교통 접근성이 취약함",
    "coreArea": "의료",
    "policyRecommendation": "집중 모니터링 및 순회방문 / 보건지소 연계 이동진료·방문진료 확대 / 인접 공공기관 또는 협력의료기관 거점 지정"
  },
  "성환읍": {
    "name": "성환읍",
    "district": "서북구",
    "kind": "읍",
    "total": 21430,
    "elderly": 6823,
    "elderlyRate": 31.84,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 1401,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 533,
    "medicalInstitutions": 21,
    "publicInstitutions": 4,
    "medicalPer1000": 3.08,
    "areaKm2": 57.2244,
    "stops": 174,
    "dailySupply": 8915,
    "selectionReason": "고령인구 대비 의료기관이 부족함, 대중교통 접근성이 취약함, 고령인구 지원 규모가 큼",
    "coreArea": "교통",
    "policyRecommendation": "집중 모니터링 및 순회방문 / 예약형 셔틀·수요응답형 교통 지원"
  },
  "목천읍": {
    "name": "목천읍",
    "district": "동남구",
    "kind": "읍",
    "total": 21717,
    "elderly": 5384,
    "elderlyRate": 24.79,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 1135,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 482,
    "medicalInstitutions": 14,
    "publicInstitutions": 2,
    "medicalPer1000": 2.6,
    "areaKm2": 63.1511,
    "stops": 164,
    "dailySupply": 14161,
    "selectionReason": "고령인구 대비 의료기관이 부족함, 대중교통 접근성이 취약함",
    "coreArea": "의료",
    "policyRecommendation": "집중 모니터링 및 순회방문 / 보건지소 연계 이동진료·방문진료 확대"
  },
  "일봉동": {
    "name": "일봉동",
    "district": "동남구",
    "kind": "동",
    "total": 24213,
    "elderly": 4144,
    "elderlyRate": 17.11,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 613,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 351,
    "medicalInstitutions": 1,
    "publicInstitutions": 0,
    "medicalPer1000": 0.24,
    "areaKm2": 2.5127,
    "stops": 28,
    "dailySupply": 3972,
    "selectionReason": "공공 보건기관이 부족함, 고령인구 대비 의료기관이 부족함, 대중교통 접근성이 취약함",
    "coreArea": "의료",
    "policyRecommendation": "집중 모니터링 및 순회방문 / 보건지소 연계 이동진료·방문진료 확대 / 인접 공공기관 또는 협력의료기관 거점 지정"
  },
  "중앙동": {
    "name": "중앙동",
    "district": "동남구",
    "kind": "동",
    "total": 4395,
    "elderly": 1660,
    "elderlyRate": 37.77,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 552,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 163,
    "medicalInstitutions": 29,
    "publicInstitutions": 0,
    "medicalPer1000": 17.47,
    "areaKm2": 0.7765,
    "stops": 23,
    "dailySupply": 15101,
    "selectionReason": "독거노인 비율이 높음, 공공 보건기관이 부족함, 고령인구 대비 의료기관이 부족함",
    "coreArea": "의료",
    "policyRecommendation": "집중 모니터링 및 순회방문 / 독거노인·중증장애인 대상군 우선 확인 / 인접 공공기관 또는 협력의료기관 거점 지정"
  },
  "성거읍": {
    "name": "성거읍",
    "district": "서북구",
    "kind": "읍",
    "total": 21269,
    "elderly": 4218,
    "elderlyRate": 19.83,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 681,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 424,
    "medicalInstitutions": 6,
    "publicInstitutions": 1,
    "medicalPer1000": 1.42,
    "areaKm2": 31.7246,
    "stops": 129,
    "dailySupply": 10561,
    "selectionReason": "고령인구 대비 의료기관이 부족함, 대중교통 접근성이 취약함, 공공 보건기관이 부족함",
    "coreArea": "의료",
    "policyRecommendation": "집중 모니터링 및 순회방문 / 보건지소 연계 이동진료·방문진료 확대"
  },
  "문성동": {
    "name": "문성동",
    "district": "동남구",
    "kind": "동",
    "total": 7785,
    "elderly": 1293,
    "elderlyRate": 16.61,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 292,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 125,
    "medicalInstitutions": 8,
    "publicInstitutions": 0,
    "medicalPer1000": 6.19,
    "areaKm2": 0.6233,
    "stops": 11,
    "dailySupply": 5070,
    "selectionReason": "공공 보건기관이 부족함, 고령인구 대비 의료기관이 부족함",
    "coreArea": "의료",
    "policyRecommendation": "정기 건강관리·예방 중심 관리 / 보건지소 연계 이동진료·방문진료 확대 / 인접 공공기관 또는 협력의료기관 거점 지정"
  },
  "직산읍": {
    "name": "직산읍",
    "district": "서북구",
    "kind": "읍",
    "total": 18957,
    "elderly": 3837,
    "elderlyRate": 20.24,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 700,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 386,
    "medicalInstitutions": 18,
    "publicInstitutions": 3,
    "medicalPer1000": 4.69,
    "areaKm2": 30.4605,
    "stops": 100,
    "dailySupply": 6094,
    "selectionReason": "고령인구 대비 의료기관이 부족함, 대중교통 접근성이 취약함",
    "coreArea": "교통",
    "policyRecommendation": "정기 건강관리·예방 중심 관리 / 예약형 셔틀·수요응답형 교통 지원"
  },
  "풍세면": {
    "name": "풍세면",
    "district": "동남구",
    "kind": "면",
    "total": 10557,
    "elderly": 2216,
    "elderlyRate": 20.99,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 348,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 121,
    "medicalInstitutions": 5,
    "publicInstitutions": 3,
    "medicalPer1000": 2.26,
    "areaKm2": 30.5689,
    "stops": 101,
    "dailySupply": 3160,
    "selectionReason": "고령인구 대비 의료기관이 부족함, 대중교통 접근성이 취약함",
    "coreArea": "교통",
    "policyRecommendation": "정기 건강관리·예방 중심 관리 / 예약형 셔틀·수요응답형 교통 지원"
  },
  "성정2동": {
    "name": "성정2동",
    "district": "서북구",
    "kind": "동",
    "total": 24417,
    "elderly": 3518,
    "elderlyRate": 14.41,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 770,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 551,
    "medicalInstitutions": 50,
    "publicInstitutions": 0,
    "medicalPer1000": 14.21,
    "areaKm2": 2.1284,
    "stops": 33,
    "dailySupply": 5386,
    "selectionReason": "공공 보건기관이 부족함, 고령인구 대비 의료기관이 부족함, 대중교통 접근성이 취약함",
    "coreArea": "의료",
    "policyRecommendation": "정기 건강관리·예방 중심 관리 / 보건지소 연계 이동진료·방문진료 확대 / 인접 공공기관 또는 협력의료기관 거점 지정"
  },
  "신방동": {
    "name": "신방동",
    "district": "동남구",
    "kind": "동",
    "total": 42607,
    "elderly": 5449,
    "elderlyRate": 12.79,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 776,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 551,
    "medicalInstitutions": 41,
    "publicInstitutions": 0,
    "medicalPer1000": 7.52,
    "areaKm2": 5.412,
    "stops": 51,
    "dailySupply": 6927,
    "selectionReason": "공공 보건기관이 부족함, 고령인구 대비 의료기관이 부족함, 대중교통 접근성이 취약함",
    "coreArea": "의료",
    "policyRecommendation": "정기 건강관리·예방 중심 관리 / 보건지소 연계 이동진료·방문진료 확대 / 인접 공공기관 또는 협력의료기관 거점 지정"
  },
  "청룡동": {
    "name": "청룡동",
    "district": "동남구",
    "kind": "동",
    "total": 59960,
    "elderly": 8386,
    "elderlyRate": 13.99,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 1086,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 945,
    "medicalInstitutions": 56,
    "publicInstitutions": 0,
    "medicalPer1000": 6.68,
    "areaKm2": 16.8571,
    "stops": 107,
    "dailySupply": 20344,
    "selectionReason": "고령인구 지원 규모가 큼, 공공 보건기관이 부족함, 고령인구 대비 의료기관이 부족함",
    "coreArea": "의료",
    "policyRecommendation": "정기 건강관리·예방 중심 관리 / 보건지소 연계 이동진료·방문진료 확대 / 인접 공공기관 또는 협력의료기관 거점 지정"
  },
  "쌍용2동": {
    "name": "쌍용2동",
    "district": "서북구",
    "kind": "동",
    "total": 33638,
    "elderly": 4947,
    "elderlyRate": 14.71,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 518,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 504,
    "medicalInstitutions": 31,
    "publicInstitutions": 0,
    "medicalPer1000": 6.27,
    "areaKm2": 1.8709,
    "stops": 28,
    "dailySupply": 6163,
    "selectionReason": "공공 보건기관이 부족함, 고령인구 대비 의료기관이 부족함, 대중교통 접근성이 취약함",
    "coreArea": "의료",
    "policyRecommendation": "정기 건강관리·예방 중심 관리 / 보건지소 연계 이동진료·방문진료 확대 / 인접 공공기관 또는 협력의료기관 거점 지정"
  },
  "쌍용1동": {
    "name": "쌍용1동",
    "district": "서북구",
    "kind": "동",
    "total": 12178,
    "elderly": 2848,
    "elderlyRate": 23.39,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 356,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 231,
    "medicalInstitutions": 50,
    "publicInstitutions": 0,
    "medicalPer1000": 17.56,
    "areaKm2": 0.8269,
    "stops": 17,
    "dailySupply": 4711,
    "selectionReason": "공공 보건기관이 부족함, 고령인구 대비 의료기관이 부족함",
    "coreArea": "의료",
    "policyRecommendation": "정기 건강관리·예방 중심 관리 / 인접 공공기관 또는 협력의료기관 거점 지정"
  },
  "부성1동": {
    "name": "부성1동",
    "district": "서북구",
    "kind": "동",
    "total": 56813,
    "elderly": 5223,
    "elderlyRate": 9.19,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 602,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 565,
    "medicalInstitutions": 38,
    "publicInstitutions": 0,
    "medicalPer1000": 7.28,
    "areaKm2": 12.0644,
    "stops": 90,
    "dailySupply": 18972,
    "selectionReason": "공공 보건기관이 부족함, 고령인구 대비 의료기관이 부족함",
    "coreArea": "의료",
    "policyRecommendation": "정기 건강관리·예방 중심 관리 / 보건지소 연계 이동진료·방문진료 확대 / 인접 공공기관 또는 협력의료기관 거점 지정"
  },
  "백석동": {
    "name": "백석동",
    "district": "서북구",
    "kind": "동",
    "total": 40263,
    "elderly": 3754,
    "elderlyRate": 9.32,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 257,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 444,
    "medicalInstitutions": 27,
    "publicInstitutions": 0,
    "medicalPer1000": 7.19,
    "areaKm2": 4.5425,
    "stops": 57,
    "dailySupply": 8654,
    "selectionReason": "공공 보건기관이 부족함, 고령인구 대비 의료기관이 부족함, 대중교통 접근성이 취약함",
    "coreArea": "의료",
    "policyRecommendation": "정기 건강관리·예방 중심 관리 / 보건지소 연계 이동진료·방문진료 확대 / 인접 공공기관 또는 협력의료기관 거점 지정"
  },
  "신안동": {
    "name": "신안동",
    "district": "동남구",
    "kind": "동",
    "total": 39066,
    "elderly": 6486,
    "elderlyRate": 16.6,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 837,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 471,
    "medicalInstitutions": 109,
    "publicInstitutions": 0,
    "medicalPer1000": 16.81,
    "areaKm2": 11.452,
    "stops": 81,
    "dailySupply": 26388,
    "selectionReason": "공공 보건기관이 부족함, 고령인구 지원 규모가 큼, 고령인구 대비 의료기관이 부족함",
    "coreArea": "의료",
    "policyRecommendation": "정기 건강관리·예방 중심 관리 / 인접 공공기관 또는 협력의료기관 거점 지정"
  },
  "부성2동": {
    "name": "부성2동",
    "district": "서북구",
    "kind": "동",
    "total": 63877,
    "elderly": 3737,
    "elderlyRate": 5.85,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 352,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 521,
    "medicalInstitutions": 57,
    "publicInstitutions": 0,
    "medicalPer1000": 15.25,
    "areaKm2": 6.747,
    "stops": 74,
    "dailySupply": 8395,
    "selectionReason": "공공 보건기관이 부족함, 고령인구 대비 의료기관이 부족함, 대중교통 접근성이 취약함",
    "coreArea": "의료",
    "policyRecommendation": "정기 건강관리·예방 중심 관리 / 보건지소 연계 이동진료·방문진료 확대 / 인접 공공기관 또는 협력의료기관 거점 지정"
  },
  "불당1동": {
    "name": "불당1동",
    "district": "서북구",
    "kind": "동",
    "total": 31541,
    "elderly": 2234,
    "elderlyRate": 7.08,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 192,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 235,
    "medicalInstitutions": 27,
    "publicInstitutions": 0,
    "medicalPer1000": 12.09,
    "areaKm2": 2.3085,
    "stops": 45,
    "dailySupply": 8459,
    "selectionReason": "공공 보건기관이 부족함, 고령인구 대비 의료기관이 부족함",
    "coreArea": "의료",
    "policyRecommendation": "현행 서비스 유지 및 지표 모니터링 / 보건지소 연계 이동진료·방문진료 확대 / 인접 공공기관 또는 협력의료기관 거점 지정"
  },
  "불당2동": {
    "name": "불당2동",
    "district": "서북구",
    "kind": "동",
    "total": 37287,
    "elderly": 1528,
    "elderlyRate": 4.1,
    "ageBands": null,
    "ageComposition": null,
    "livingAlone": 131,
    "basicLiving": null,
    "lowIncome": null,
    "disabled": 228,
    "medicalInstitutions": 91,
    "publicInstitutions": 0,
    "medicalPer1000": 59.55,
    "areaKm2": 2.2819,
    "stops": 35,
    "dailySupply": 5994,
    "selectionReason": "공공 보건기관이 부족함, 대중교통 접근성이 취약함",
    "coreArea": "교통",
    "policyRecommendation": "현행 서비스 유지 및 지표 모니터링 / 인접 공공기관 또는 협력의료기관 거점 지정"
  }
};

export const REGION_DASHBOARD_DATA: Record<string, RegionDashboardRecord> = Object.fromEntries(
  Object.entries(REGION_DATA_BY_NAME).map(([name, value]) => [REGION_CODE_BY_NAME[name] ?? name, value]),
);
